#!/bin/sh
#
# ACQ100S suspend/resume workaround
#
# /usr/lib/systemd/system-sleep/acq100s
# Set ownership to root and permissions to 755
# 

DEVICE="0000:09:00.0"
MODULE="atlantic"

case "$1" in
    pre)
        echo "ACQ100S-Fix: [PRE] Unloading $MODULE module"
        # Unload the module before suspend
        modprobe -r "$MODULE" 2>/dev/null
        ;;
    post)
        echo "ACQ100S-Fix: [POST] Reloading $MODULE module"
        # Reload the module after resume
        modprobe "$MODULE" 2>/dev/null
        # echo 1 > /sys/bus/pci/devices/$DEVICE/remove
        # echo 1 > /sys/bus/pci/rescan  
        ;;
esac

exit 0
